log:
  level: DEBUG
  shift_age: 0
  logdev: STDOUT 
  shift_size: 1048576
  datetime_format: \%Y-%m-%d %H:%M:%S

db: production

media_destination:
  stage_path: /var/www/testfiles_stage
  type: disk
  path: /var/www/testfiles_destination

media_kernel:
  base_url: http://localhost:3000/

jobs:
  - songs_from_disk:
      media_type: audio
      medias:
        - high:
            type: AAC_LC
            bit_rate: 128
            extension: m4a
        - medium:
            type: AAC_HE
            bit_rate: 96
            extension: m4a
        - low:
            type: AAC_HEv2
            bit_rate: 64
            extension: m4a
      from:
        - disk:
            path: /media/Data/Projects/nextplatform/testfiles/Media Sample
            filter: ^(.*).m4a$

